# Generated by Django 5.2.7 on 2025-10-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_destination_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='destination',
        ),
        migrations.AlterField(
            model_name='delegation',
            name='going_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوجهة'),
        ),
    ]
