# Generated by Django 5.2.7 on 2025-10-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Fake migration - database already matches schema
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
    ]
