# Generated by Django 5.2.7 on 2025-10-10 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخط الجوي')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود الخط الجوي')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airlines', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الخط الجوي',
                'verbose_name_plural': 'الخطوط الجوية',
                'db_table': 'airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المطار')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المطار')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المطار',
                'verbose_name_plural': 'المطارات',
                'db_table': 'airports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_DEPARTED', 'لم يغادر'), ('PARTIALLY_DEPARTED', 'غادر جزئياً'), ('FULLY_DEPARTED', 'غادر بالكامل')], default='NOT_DEPARTED', max_length=20, verbose_name='حالة الوفد')),
                ('type', models.CharField(choices=[('MILITARY', 'عسكري'), ('CIVILIAN', 'مدني')], max_length=20, verbose_name='نوع الوفد')),
                ('arrival_info', models.JSONField(default=dict, verbose_name='معلومات الوصول')),
                ('max_members', models.IntegerField(default=0, verbose_name='الحد الأقصى للأعضاء')),
                ('current_members', models.IntegerField(default=0, verbose_name='العدد الحالي للأعضاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الوفد',
                'verbose_name_plural': 'الوفود',
                'db_table': 'delegations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_info', models.JSONField(default=dict, verbose_name='معلومات المغادرة')),
                ('session_type', models.CharField(choices=[('PARTIAL', 'جزئية'), ('FULL', 'كاملة')], max_length=20, verbose_name='نوع الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departure_sessions', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_sessions', to='api.delegation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departure_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسة المغادرة',
                'verbose_name_plural': 'جلسات المغادرة',
                'db_table': 'departure_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحدث')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_main_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_main_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الحدث الرئيسي',
                'verbose_name_plural': 'الأحداث الرئيسية',
                'db_table': 'main_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم العضو')),
                ('rank', models.CharField(max_length=100, verbose_name='الرتبة')),
                ('position', models.CharField(max_length=200, verbose_name='المنصب')),
                ('equivalent_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='المنصب المكافئ')),
                ('status', models.CharField(choices=[('NOT_DEPARTED', 'لم يغادر'), ('DEPARTED', 'غادر')], default='NOT_DEPARTED', max_length=20, verbose_name='حالة العضو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.delegation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilitaryPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنصب')),
                ('equivalent_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='المنصب المكافئ')),
                ('rank_level', models.IntegerField(default=0, verbose_name='مستوى الرتبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_military_positions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_military_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المنصب العسكري',
                'verbose_name_plural': 'المناصب العسكرية',
                'db_table': 'military_positions',
                'ordering': ['rank_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الجنسية')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='كود الجنسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nationalities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nationalities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الجنسية',
                'verbose_name_plural': 'الجنسيات',
                'db_table': 'nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delegation',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.nationality'),
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحدث الفرعي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_events', to=settings.AUTH_USER_MODEL)),
                ('main_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='api.mainevent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sub_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الحدث الفرعي',
                'verbose_name_plural': 'الأحداث الفرعية',
                'db_table': 'sub_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='delegation',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.subevent'),
        ),
    ]
