# Generated by Django 5.2.7 on 2025-10-12 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم شركة الطيران')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airlines', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شركة الطيران',
                'verbose_name_plural': 'شركات الطيران',
                'db_table': 'air_line',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المطار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المطار',
                'verbose_name_plural': 'المطارات',
                'db_table': 'air_port',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100, unique=True, verbose_name='اسم المدينة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المدينة',
                'verbose_name_plural': 'المدن',
                'db_table': 'cities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegation_leader_name', models.CharField(max_length=100, verbose_name='اسم رئيس الوفد')),
                ('member_count', models.IntegerField(default=0, verbose_name='عدد الأعضاء المحدد للوفد')),
                ('current_members', models.IntegerField(default=0, verbose_name='العدد الحالي للأعضاء')),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الرحلة')),
                ('type', models.CharField(choices=[('MILITARY', 'عسكري'), ('CIVILIAN', 'مدني')], max_length=20, verbose_name='نوع الوفد')),
                ('status', models.CharField(choices=[('NOT_DEPARTED', 'لم يغادر أحد'), ('PARTIALLY_DEPARTED', 'غادر جزء من الأعضاء'), ('FULLY_DEPARTED', 'غادر جميع الأعضاء')], default='NOT_DEPARTED', max_length=20, verbose_name='حالة الوفد')),
                ('arrive_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول')),
                ('arrive_time', models.TimeField(blank=True, null=True, verbose_name='ساعة الوصول')),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستقبل')),
                ('going_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوجهة')),
                ('goods', models.TextField(blank=True, null=True, verbose_name='الشحنات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_id', models.ForeignKey(blank=True, db_column='airline_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations', to='api.airline')),
                ('airport_id', models.ForeignKey(blank=True, db_column='airport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations', to='api.airport')),
                ('city_id', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations', to='api.cities')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الوفد',
                'verbose_name_plural': 'الوفود',
                'db_table': 'delegation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquivalentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوظيفة المعادلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equivalent_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equivalent_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الوظيفة المعادلة',
                'verbose_name_plural': 'الوظائف المعادلة',
                'db_table': 'equivalent_job',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100, verbose_name='اسم الحدث الرئيسي')),
                ('event_link', models.TextField(blank=True, null=True, verbose_name='رابط الحدث')),
                ('event_icon', models.TextField(blank=True, null=True, verbose_name='أيقونة الحدث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_main_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_main_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الحدث الرئيسي',
                'verbose_name_plural': 'الأحداث الرئيسية',
                'db_table': 'main_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرتبة العسكرية')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العضو')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة/الدور الحالي')),
                ('status', models.CharField(choices=[('NOT_DEPARTED', 'لم يغادر'), ('DEPARTED', 'غادر')], default='NOT_DEPARTED', max_length=20, verbose_name='حالة العضو')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة الفعلي للعضو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('delegation_id', models.ForeignKey(db_column='delegation_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.delegation')),
                ('equivalent_job_id', models.ForeignKey(blank=True, db_column='equivalent_job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.equivalentjob')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'db_table': 'member',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الجنسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nationalities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nationalities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الجنسية',
                'verbose_name_plural': 'الجنسيات',
                'db_table': 'nationality',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delegation',
            name='nationality_id',
            field=models.ForeignKey(blank=True, db_column='nationality_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations', to='api.nationality'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم رحلة المغادرة')),
                ('checkout_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة')),
                ('checkout_time', models.TimeField(blank=True, null=True, verbose_name='ساعة المغادرة')),
                ('depositor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المودع')),
                ('goods', models.TextField(blank=True, null=True, verbose_name='الشحنات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('members', models.JSONField(default=list, verbose_name='قائمة الأعضاء في هذه الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_id', models.ForeignKey(blank=True, db_column='airline_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.airline')),
                ('airport_id', models.ForeignKey(blank=True, db_column='airport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.airport')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_check_outs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_check_outs', to=settings.AUTH_USER_MODEL)),
                ('city_id', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.cities')),
                ('delegation_id', models.ForeignKey(db_column='delegation_id', on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='api.delegation')),
                ('nationality_id', models.ForeignKey(blank=True, db_column='nationality_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.nationality')),
            ],
            options={
                'verbose_name': 'جلسة المغادرة',
                'verbose_name_plural': 'جلسات المغادرة',
                'db_table': 'check_out',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100, verbose_name='اسم الحدث الفرعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_events', to=settings.AUTH_USER_MODEL)),
                ('main_event_id', models.ForeignKey(db_column='main_event_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='api.mainevent')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sub_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الحدث الفرعي',
                'verbose_name_plural': 'الأحداث الفرعية',
                'db_table': 'sub_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='delegation',
            name='sub_event_id',
            field=models.ForeignKey(db_column='sub_event_id', on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.subevent'),
        ),
    ]
