# Generated by Django 5.2.7 on 2025-10-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوجهة (الفندق)'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='going_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوجهة (قادمة من)'),
        ),
    ]
