# Generated by Django 5.2.7 on 2025-10-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airline',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airport',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airport',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departuresession',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departure_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departuresession',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departure_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_main_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_main_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='militaryposition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_military_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='militaryposition',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_military_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nationalities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nationalities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sub_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
