# Generated by Django 5.2.7 on 2025-10-18 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_destination_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='airline_id',
            field=models.ForeignKey(blank=True, db_column='airline_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.airline'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='airport_id',
            field=models.ForeignKey(blank=True, db_column='airport_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.airport'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.cities'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='nationality_id',
            field=models.ForeignKey(blank=True, db_column='nationality_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.nationality'),
        ),
    ]
