# Generated by Django 5.2.7 on 2025-10-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_delegation_airline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='airline_id',
            field=models.ForeignKey(blank=True, db_column='airline_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.airline'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='airport_id',
            field=models.ForeignKey(blank=True, db_column='airport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.airport'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.cities'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='nationality_id',
            field=models.ForeignKey(blank=True, db_column='nationality_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='api.nationality'),
        ),
    ]
